version: '3.8'

services:
  backend:
    image: freeapi-server
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/freeapi
      - /usr/src/freeapi/node_modules
    env_file:
      - ./.env
#    extra_hosts:
#      - "host.docker.internal:host-gateway" 
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017

volumes:
  data:
