version: '3.8'

services:
  backend:
    image: freeapi-server
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/freeapi
      - /usr/src/freeapi/node_modules
    env_file:
      - ./.env
    environment:
      - MONGODB_URI=mongodb://172.17.0.1:27017

volumes:
  data:
